### PR TITLE
Add Darwin arm64 Support

### PR DESCRIPTION
**Pull request by tolumide-ng**
- Adds Support for darwin-arm64
- Updates `.gitignore`

### CODE REVIEW

**Comment by deevus** [comment]
@tolumide-ng Thanks I will get to it this week.

**Comment by tolumide-ng** [comment]
Hello, @deevus I hope you're having a great day. Apologies for any inconvenience. I would like to ask if there are any updates on this PR from your end.

**Review by deevus — APPROVED** [review]

**Comment by tolumide-ng** [comment]
Hello, @deevus thank you once again for the merge and your time. I would like to ask if the new master would be published to `npm` soon.

**Comment by deevus** [comment]
Soon! :)

**Comment by deevus** [comment]
@tolumide-ng This has been published.

**Comment by tolumide-ng** [comment]
Thank you @deevus

**Pull request merged**
