### PR TITLE
feat(ffmpeg): Update version to 4.3.1

### PR DESCRIPTION
**Pull request by eliotik**
Updated ffmpeg binaries for:
- darwin, linux platforms
- windows platform skipped

### CODE REVIEW

**Comment by eliotik** [comment]
Hi @kribblo , can you  please merge it and then do platform/* `npm run upload`?
I cannot  upload new version of ffmpeg binaries to npm registry since I'm not owner of these optional repositories.

**Comment by whyboris** [comment]
Looks like there's a `fork` that is more up to date 🤔 
https://github.com/devdanim/dnm-node-ffmpeg-installer

**Comment by whyboris** [comment]
There's also this: https://github.com/SavageCore/node-ffprobe-installer 🤔  unsure if it's a good alternative

**Comment by deevus** [comment]
Yo what's the hold on this @kribblo

**Comment by deevus** [comment]
@eliotik Are you able to update these to 4.3.2 and squash?

**Comment by deevus** [comment]
For Windows builds, can we use https://github.com/GyanD/codexffmpeg

**Comment by deevus** [comment]
Or https://github.com/BtbN/FFmpeg-Builds

**Comment by deevus** [comment]
@whyboris @eliotik Any thoughts on #53?

**Comment by goatandsheep** [comment]
fixes #36

**Pull request closed without merging**
